epoch: 300
LearningRate:
  base_lr: 0.001
  schedulers:
  - !YoloxWarmCosDecay
    max_epochs: 300
    warmup_epochs: 5
    warmup_lr_start: 0
    no_aug_epochs: 15
    min_lr_ratio: 0.05

OptimizerBuilder:
  optimizer:
    type: Momentum
    momentum: 0.9
    use_nesterov: true
  regularizer:
    factor: 0.0005
    type: L2