worker_num: 1
TrainReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    - YoloxTransform: {}

  batch_size: 1
  shuffle: true
  drop_last: true
  mosaic_epoch: 285
  use_shared_memory: true

EvalReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - Pad: {size: [640, 640], pad_mode: 0, fill_value: [114.0, 114.0, 114.0]}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - Pad: {size: [640, 640], pad_mode: 0, fill_value: [114.0, 114.0, 114.0]}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
