metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/sample.json
    dataset_dir: /f/dataset/COCO2017
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /f/dataset/COCO2017

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json
